# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# Use U-Boot's per-SoC overlay address as scratch buffer.
# RK3576: 0x48200000, RK3588: 0x08200000 (set in ENV_MEM_LAYOUT_SETTINGS)
setenv load_addr "${fdtoverlay_addr_r}"
setenv overlay_error "false"
# default values
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "off"
setenv eeprom_dtb_select "on"

test -n "${distro_bootpart}" || distro_bootpart=1

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

# Load armbianEnv.txt with corruption detection and .dist fallback.
# Power loss can fill the file with 0xFF (eMMC erased block) or ^@ (NUL,
# on other storage media) which passes "env import -t" without error but
# imports zero variables. Clear rootdev before import; if it remains
# empty, the file was corrupt.
setenv rootdev
if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt; then
	env import -t ${load_addr} ${filesize}
fi
if test -z "${rootdev}"; then
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt.dist; then
		echo "WARNING: armbianEnv.txt corrupt, loading .dist fallback"
		setenv rootdev
		env import -t ${load_addr} ${filesize}
	fi
fi
# Final safety: derive rootdev from boot source if still unset
if test -z "${rootdev}"; then
	echo "WARNING: rootdev not set, deriving from boot source ${devtype} ${devnum}:${distro_bootpart}"
	if test "${devtype}" = "nvme"; then
		setenv rootdev "/dev/nvme${devnum}n1p${distro_bootpart}"
	else
		setenv rootdev "/dev/mmcblk${devnum}p${distro_bootpart}"
	fi
fi

# fdtfile is set by armbianEnv.txt (per-board BOOT_FDT_FILE).
# EEPROM detection below will override it if a valid EEPROM is found.
setenv eeprom_dtb_matched "no"

# EEPROM format:
#   [0..5]  = "rk35xx"
#   [6..9]  = board code, e.g. 00A0 / 00B0
#   [10.. ] = SN (ignored by boot logic)
# Read EEPROM from i2c4@0x57 and override fdtfile if format matches.
if test "${eeprom_dtb_select}" = "on"; then
	if i2c dev 4; then
		if i2c read 0x57 0x0.2 10 ${load_addr}; then
			setexpr.b ee0 *${load_addr}
			setexpr tmp ${load_addr} + 1
			setexpr.b ee1 *${tmp}
			setexpr tmp ${load_addr} + 2
			setexpr.b ee2 *${tmp}
			setexpr tmp ${load_addr} + 3
			setexpr.b ee3 *${tmp}
			setexpr tmp ${load_addr} + 4
			setexpr.b ee4 *${tmp}
			setexpr tmp ${load_addr} + 5
			setexpr.b ee5 *${tmp}

			if test "${ee0}" = "0x72" && test "${ee1}" = "0x6b" && test "${ee2}" = "0x33" && test "${ee3}" = "0x35" && test "${ee4}" = "0x78" && test "${ee5}" = "0x78"; then
				setexpr tmp ${load_addr} + 6
				setexpr.b code0 *${tmp}
				setexpr tmp ${load_addr} + 7
				setexpr.b code1 *${tmp}
				setexpr tmp ${load_addr} + 8
				setexpr.b code2 *${tmp}
				setexpr tmp ${load_addr} + 9
				setexpr.b code3 *${tmp}

				# 00A0 -> rk3576 dtb
				if test "${code0}" = "0x30" && test "${code1}" = "0x30" && test "${code2}" = "0x41" && test "${code3}" = "0x30"; then
					setenv fdtfile "rockchip/rk3576-recomputer-rk3576-devkit.dtb"
					setenv eeprom_dtb_matched "yes"
					echo "Detected board: reComputer RK3576 Devkit, using DTB: ${fdtfile}"
				# 00B0 -> rk3588 dtb
				elif test "${code0}" = "0x30" && test "${code1}" = "0x30" && test "${code2}" = "0x42" && test "${code3}" = "0x30"; then
					setenv fdtfile "rockchip/rk3588-recomputer-rk3588-devkit.dtb"
					setenv eeprom_dtb_matched "yes"
					echo "Detected board: reComputer RK3588 Devkit, using DTB: ${fdtfile}"
				fi
			fi
		fi
	fi
fi

if test "${eeprom_dtb_matched}" != "yes"; then
	echo "No valid EEPROM information detected, using default DTB: ${fdtfile}"
fi

echo "Using fdtfile=${fdtfile}"

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyFIQ0,1500000n8 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of the partition the boot script was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi
if test "${devtype}" = "nvme"; then part uuid nvme ${devnum}:${distro_bootpart} partuuid; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"
if test -n "${cryptdevice}"; then setenv bootargs "${bootargs} cryptdevice=${cryptdevice}"; fi

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	elif load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
if test "${overlay_error}" = "true"; then
	echo "Error applying DT overlays, restoring original DT"
	load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}
else
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}dtb/rockchip/overlay/${overlay_prefix}-fixup.scr
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}fixup.scr; then
		load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

echo "Trying 'kaslrseed' command... Info: 'Unknown command' can be safely ignored since 'kaslrseed' does not apply to all boards."
kaslrseed # @TODO: This gives an error (Unknown command ' kaslrseed ' - try 'help') on many devices since CONFIG_CMD_KASLRSEED is not enabled
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
