#!/bin/bash
#========================================================================================
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the Rebuild Armbian
# https://github.com/ophub/amlogic-s9xxx-armbian
#
# Dependent script: /usr/lib/armbian/armbian-firstrun
# Function: Fix permissions and system settings (executed during initial system setup)
# Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
#
# Command: armbian-fix
#
#================================ Set default parameters ================================
#
export DEBIAN_FRONTEND=noninteractive

# Set the armbian release check file
armbian_release_file="/etc/armbian-release"
armbian_image_file="/etc/armbian-image-release"
armbian_os_status="/etc/armbian-distribution-status"
os_release_file="/etc/os-release"
# Set the ophub release check file
ophub_release_file="/etc/ophub-release"
# Custom armbian-fix Log
fix_log="/tmp/armbian-fix.log"
#
#======================================================================================

# Add log
tolog() {
    echo -e "${1}"
    echo -e "[$(date +"%Y.%m.%d.%H:%M:%S")] ${1}" >>"${fix_log}" 2>/dev/null || true
}

# Show start message
echo "" >${fix_log} && tolog "Starting system fixes..."

# Get the system release version, such as: resolute, noble, trixie, bookworm, etc.
[[ -f "/etc/lsb-release" ]] && DISTRIBUTION_CODENAME="$(grep CODENAME /etc/lsb-release | cut -d'=' -f2 || true)"
[[ -z "${DISTRIBUTION_CODENAME}" && -f "${os_release_file}" ]] && DISTRIBUTION_CODENAME="$(grep VERSION_CODENAME "${os_release_file}" | cut -d'=' -f2 || true)"
[[ -z "${DISTRIBUTION_CODENAME}" && -x "/usr/bin/lsb_release" ]] && DISTRIBUTION_CODENAME="$(/usr/bin/lsb_release -c | cut -d':' -f2 | tr -d '\t' || true)"

# ===== A. Fix system permissions =====

# Fix common release permissions
[[ -d "/var/tmp" ]] && chmod 777 /var/tmp 2>/dev/null && tolog "01. Fix tmp permissions"
[[ -d "/etc/update-motd.d" ]] && chmod -x /etc/update-motd.d/* 2>/dev/null && chmod +x /etc/update-motd.d/{10-*,20-*,30-*} 2>/dev/null && tolog "02. Fix update-motd.d permissions"
[[ -d "/var/cache/man" ]] && chown man:root /var/cache/man -R 2>/dev/null && tolog "03. Fix man permissions"
[[ -d "/var/cache/man" ]] && chmod g+s /var/cache/man -R 2>/dev/null && tolog "04. Fix man permissions"
[[ -f "/etc/sudoers" ]] && chown root:root /etc/sudoers 2>/dev/null && tolog "05. Fix sudoers ownership"
[[ -f "/etc/sudoers" ]] && chmod 440 /etc/sudoers 2>/dev/null && tolog "06. Fix sudoers permissions"
[[ -f "/usr/bin/sudo" ]] && chown root:root /usr/bin/sudo 2>/dev/null && tolog "07. Fix sudo permissions"
[[ -f "/usr/bin/sudo" ]] && chmod 4755 /usr/bin/sudo 2>/dev/null && tolog "08. Fix sudo permissions"
# Fix focal permissions
[[ -f "/usr/lib/sudo/sudoers.so" ]] && chown 0 /usr/lib/sudo/sudoers.so 2>/dev/null && tolog "09. Fix sudoers.so permissions"
[[ -f "/usr/lib/sudo/sudoers.so" ]] && chmod 644 /usr/lib/sudo/sudoers.so 2>/dev/null && tolog "10. Fix sudoers.so permissions"
[[ -f "/usr/lib/policykit-1/polkit-agent-helper-1" ]] && chmod 4755 /usr/lib/policykit-1/polkit-agent-helper-1 2>/dev/null && tolog "11. Fix polkit-agent-helper-1 permissions"
# Fix jammy permissions
[[ -f "/usr/libexec/sudo/sudoers.so" ]] && chown 0 /usr/libexec/sudo/sudoers.so 2>/dev/null && tolog "12. Fix sudoers.so permissions"
[[ -f "/usr/libexec/sudo/sudoers.so" ]] && chmod 644 /usr/libexec/sudo/sudoers.so 2>/dev/null && tolog "13. Fix sudoers.so permissions"
[[ -f "/usr/libexec/polkit-agent-helper-1" ]] && chmod 4755 /usr/libexec/polkit-agent-helper-1 2>/dev/null && tolog "14. Fix polkit-agent-helper-1 permissions"

# ===== B. Remove unnecessary packages and scripts =====

# Clean APT cache
apt-get clean -y 2>/dev/null && rm -rf /var/cache/apt/* 2>/dev/null && rm -rf /var/lib/apt/* 2>/dev/null && tolog "20. Clean APT cache"

# Get kernel signature
[[ -f "${ophub_release_file}" ]] && {
    kernel_signature="$(cat ${ophub_release_file} | grep -E "^KERNEL_SIGNATURE=" | cut -d"'" -f2 || true)"
}

# 21. Remove linux-image-*
pkg_linux_image="$(dpkg -l | awk '{print $2}' | grep "^linux-image-" || true)"
for pkg in ${pkg_linux_image}; do
    if [[ -n "${pkg}" ]] && [[ -z "${kernel_signature}" || ! "${pkg}" =~ ${kernel_signature} ]]; then
        image_list_path="/var/lib/dpkg/info/${pkg}.list"
        apt-mark unhold ${pkg} 2>/dev/null
        truncate -s 0 "${image_list_path}" 2>/dev/null || : >"${image_list_path}" 2>/dev/null
        apt-get remove -qq --purge -y --allow-change-held-packages ${pkg} 2>/dev/null && tolog "21. Remove ${pkg}"
    elif [[ "${pkg}" =~ ${kernel_signature} ]]; then
        tolog "21. Keep ${pkg}"
    fi
done

# 22. Remove linux-dtb-*
pkg_linux_dtb="$(dpkg -l | awk '{print $2}' | grep "^linux-dtb-" || true)"
for pkg in ${pkg_linux_dtb}; do
    if [[ -n "${pkg}" ]] && [[ -z "${kernel_signature}" || ! "${pkg}" =~ ${kernel_signature} ]]; then
        dtb_list_path="/var/lib/dpkg/info/${pkg}.list"
        apt-mark unhold ${pkg} 2>/dev/null
        truncate -s 0 "${dtb_list_path}" 2>/dev/null || : >"${dtb_list_path}" 2>/dev/null
        apt-get remove -qq --purge -y --allow-change-held-packages ${pkg} 2>/dev/null && tolog "22. Remove ${pkg}"
    elif [[ "${pkg}" =~ ${kernel_signature} ]]; then
        tolog "22. Keep ${pkg}"
    fi
done

# 23. Remove linux-u-boot-*
pkg_linux_uboot="$(dpkg -l | awk '{print $2}' | grep "^linux-u-boot-" || true)"
for pkg in ${pkg_linux_uboot}; do
    if [[ -n "${pkg}" ]]; then
        linux_uboot_list_path="/var/lib/dpkg/info/${pkg}.list"
        apt-mark unhold ${pkg} 2>/dev/null
        truncate -s 0 "${linux_uboot_list_path}" 2>/dev/null || : >"${linux_uboot_list_path}" 2>/dev/null
        apt-get remove -qq --purge -y --allow-change-held-packages ${pkg} 2>/dev/null && tolog "23. Remove ${pkg}"
    fi
done

# 24. Remove armbian-firmware
pkg_armbian_firmware="$(dpkg -l | awk '{print $2}' | grep "^armbian-firmware" || true)"
for pkg in ${pkg_armbian_firmware}; do
    if [[ -n "${pkg}" ]]; then
        firmware_list_path="/var/lib/dpkg/info/${pkg}.list"
        apt-mark unhold ${pkg} 2>/dev/null
        truncate -s 0 "${firmware_list_path}" 2>/dev/null || : >"${firmware_list_path}" 2>/dev/null
        apt-get remove -qq --purge -y --allow-change-held-packages ${pkg} 2>/dev/null && tolog "24. Remove ${pkg}"
    fi
done

# 25. Remove armbian-bsp-cli-*
pkg_armbian_bsp_cli="$(dpkg -l | awk '{print $2}' | grep "^armbian-bsp-cli-" || true)"
for pkg in ${pkg_armbian_bsp_cli}; do
    if [[ -n "${pkg}" ]]; then
        armbian_bsp_cli_list_path="/var/lib/dpkg/info/${pkg}.list"
        apt-mark unhold ${pkg} 2>/dev/null
        truncate -s 0 "${armbian_bsp_cli_list_path}" 2>/dev/null || : >"${armbian_bsp_cli_list_path}" 2>/dev/null
        apt-get remove -qq --purge -y --allow-change-held-packages ${pkg} 2>/dev/null && tolog "25. Remove ${pkg}"
    fi
done

# 26. hold packages and disable update_initramfs
[[ -n "$(dpkg -l | awk '{print $2}' | grep initramfs-tools || true)" ]] && apt-mark hold initramfs-tools* 2>/dev/null && tolog "26. Hold initramfs-tools*"
initramfs_conf="/etc/initramfs-tools/update-initramfs.conf"
[[ -f "${initramfs_conf}" ]] && sed -i "s|^update_initramfs=.*|update_initramfs=no|g" "${initramfs_conf}" && tolog "27. Disable update-initramfs.conf"

# ===== C. Disable unnecessary system services =====

# Regenerate machine-id for unique identification
rm -f /etc/machine-id /var/lib/dbus/machine-id 2>/dev/null && tolog "50. Delete machine-id"
dbus-uuidgen --ensure=/etc/machine-id 2>/dev/null && tolog "51. Generate /etc/machine-id"
dbus-uuidgen --ensure 2>/dev/null && tolog "52. Generate /var/lib/dbus/machine-id"

# Disable automatic hibernation to prevent storage device issues
systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target 2>/dev/null && tolog "53. Disable automatic sleep/hibernation"

# Disable tips of the day for [ /etc/update-motd.d/35-armbian-tips ]
motd_tips="/etc/default/armbian-motd"
[[ -f "${motd_tips}" ]] && {
    sed -i 's|^MOTD_DISABLE=""|MOTD_DISABLE="tips"|g' "${motd_tips}"
    tolog "54. Disable tips of the day"
} || true
quotes_cron="/etc/cron.daily/armbian-quotes"
[[ -f "${quotes_cron}" ]] && {
    sed -i "s|^curl |#curl |g" "${quotes_cron}"
    tolog "55. Disable quotes cron plan"
} || true

# Remove motd-news services
motd_timer="/usr/lib/systemd/system/motd-news.timer"
[[ -f "${motd_timer}" ]] && {
    systemctl stop motd-news.timer 2>/dev/null
    systemctl disable motd-news.timer 2>/dev/null
    rm -f "${motd_timer}"
    tolog "56. Disable motd-news.timer"
} || true
motd_service="/usr/lib/systemd/system/motd-news.service"
[[ -f "${motd_service}" ]] && {
    systemctl stop motd-news.service 2>/dev/null
    systemctl disable motd-news.service 2>/dev/null
    rm -f "${motd_service}"
    tolog "57. Disable motd-news.service"
} || true
rm -f /var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/motd-news.timer 2>/dev/null
rm -f /var/lib/systemd/deb-systemd-helper-enabled/motd-news.timer.dsh-also 2>/dev/null
rm -f /etc/systemd/system/timers.target.wants/motd-news.timer 2>/dev/null

# Disable the partition auto-resize service
systemctl stop armbian-resize-filesystem.service 2>/dev/null
systemctl disable armbian-resize-filesystem.service 2>/dev/null
tolog "58. Disable armbian-resize-filesystem.service"

# Disable the ssh.socket: https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1476
systemctl disable --now ssh.socket 2>/dev/null
systemctl enable --now ssh.service 2>/dev/null
tolog "59. Disable the ssh.socket and enable ssh.service"

# ===== D. Apply custom settings =====

# Fix legacy configuration file names (after 2022.12.03)
[[ -f "/etc/amlogic_model_database.conf" ]] && {
    mv -f /etc/amlogic_model_database.conf /etc/model_database.conf 2>/dev/null
    tolog "70. Rename amlogic_model_database.conf to model_database.conf"
} || true

[[ -f "/etc/rockchip_model_database.conf" ]] && {
    mv -f /etc/rockchip_model_database.conf /etc/model_database.conf 2>/dev/null
    tolog "71. Rename rockchip_model_database.conf to model_database.conf"
} || true

# Confirm and adjust device information
[[ -f "${ophub_release_file}" ]] && {
    # Get welcome banner value
    family_name="$(cat ${ophub_release_file} | grep -E "^FAMILY=" | cut -d"'" -f2 || true)"
    platform_name="$(cat ${ophub_release_file} | grep -E "^PLATFORM=" | cut -d"'" -f2 || true)"
    soc_name="$(cat ${ophub_release_file} | grep -E "^SOC=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g" || true)"
    board_name="$(cat ${ophub_release_file} | grep -E "^BOARD=" | cut -d"'" -f2 | sed -e "s|\b[a-z]|\U&|g" || true)"

    # Migrate legacy ANDROID_UBOOT parameter name
    [[ -n "$(cat ${ophub_release_file} | grep -E "^ANDROID_UBOOT=")" ]] && {
        sed -i "s|^ANDROID_UBOOT=|BOOTLOADER_IMG=|g" ${ophub_release_file}
        tolog "80. Rename ANDROID_UBOOT to BOOTLOADER_IMG"
    }

    # Migrate legacy UBOOT_STATUS parameter name
    [[ -n "$(cat ${ophub_release_file} | grep -E "^UBOOT_STATUS=")" ]] && {
        sed -i "s|^UBOOT_STATUS=|MLUBOOT_STATUS=|g" ${ophub_release_file}
        tolog "81. Rename UBOOT_STATUS to MLUBOOT_STATUS"
    }

    # Add default kernel tags if missing
    sed -i "s|^KERNEL_BRANCH=|KERNEL_TAGS=|g" ${ophub_release_file}
    sed -i "s|^KERNEL_TAGS='6.x.y'|KERNEL_TAGS='6.1.y'|g" ${ophub_release_file}
    [[ -n "$(cat ${ophub_release_file} | grep -E "^KERNEL_TAGS=")" ]] || {
        [[ "${soc_name,,}" == "rk3588" ]] && KERNEL_TAGS="rk3588" || KERNEL_TAGS="stable"
        echo "KERNEL_TAGS='${KERNEL_TAGS}'" >>${ophub_release_file}
        tolog "82. Add the KERNEL_TAGS name"
    }

    # Add default KERNEL_REPO if missing
    [[ -n "$(cat ${ophub_release_file} | grep -E "^KERNEL_REPO=")" ]] || {
        echo "KERNEL_REPO='ophub/kernel'" >>${ophub_release_file}
        tolog "83. Add the custom KERNEL_REPO URL"
    }

    # Add default KERNEL_BACKUP if missing
    [[ -n "$(cat ${ophub_release_file} | grep -E "^KERNEL_BACKUP=")" ]] || {
        echo "KERNEL_BACKUP='yes'" >>${ophub_release_file}
        tolog "84. Add the custom KERNEL_BACKUP"
    }

    # Get the board display name by platform
    [[ "${platform_name}" == "amlogic" ]] && bd_name="Aml.${soc_name}"
    [[ "${platform_name}" == "rockchip" ]] && bd_name="RK.${board_name}"
    [[ "${platform_name}" == "allwinner" ]] && bd_name="AW.${board_name}"

    # Update armbian-release configuration
    [[ -f "${armbian_release_file}" ]] && {
        [[ -n "${bd_name}" ]] && {
            sed -i "s|^BOARD=.*|BOARD=\"${board_name}\"|g" ${armbian_release_file}
            sed -i "s|^BOARD_NAME=.*|BOARD_NAME=\"${bd_name}\"|g" ${armbian_release_file}
        }

        short_version="$(cat ${armbian_release_file} | grep -E '^VERSION=' | grep -oE '[2-9][0-9]\.[0-9]{1,2}\.[0-9]{1,2}' | head -n 1 || true)"
        [[ -n "${short_version}" ]] && {
            sed -i "s|^VERSION=.*|VERSION=\"${short_version}\"|g" ${armbian_release_file}
            sed -i "s|^REVISION=.*|REVISION=\"${short_version}\"|g" ${armbian_release_file}
        }

        sed -i "s|^BOOT_SOC=.*|BOOT_SOC=\"${soc_name}\"|g" ${armbian_release_file}
        sed -i "s|^BOARDFAMILY=.*|BOARDFAMILY=\"${family_name}\"|g" ${armbian_release_file}
        sed -i "s|^LINUXFAMILY=.*|LINUXFAMILY=\"${platform_name}\"|g" ${armbian_release_file}
        sed -i "s|^VENDOR=.*|VENDOR=\"Armbian OS\"|g" ${armbian_release_file}
        sed -i "s|^IMAGE_TYPE=.*|IMAGE_TYPE=rebuild|g" ${armbian_release_file}
        sed -i "s|^BOARD_TYPE=.*|BOARD_TYPE=diy|g" ${armbian_release_file}
        sed -i "s|^FORCE_BOOTSCRIPT_UPDATE=.*|FORCE_BOOTSCRIPT_UPDATE=\"no\"|g" ${armbian_release_file}
        sed -i "s|^BOOTSCRIPT_FORCE_UPDATE=.*|BOOTSCRIPT_FORCE_UPDATE=\"no\"|g" ${armbian_release_file}
        sed -i "s|^FORCE_UBOOT_UPDATE=.*|FORCE_UBOOT_UPDATE=\"no\"|g" ${armbian_release_file}
        tolog "85. Update custom board info: ${armbian_release_file}"
    }

    # Update armbian-image-release configuration
    [[ -f "${armbian_image_file}" ]] && {
        [[ -n "${bd_name}" ]] && {
            sed -i "s|^BOARD=.*|BOARD=\"${board_name}\"|g" ${armbian_image_file}
            sed -i "s|^BOARD_NAME=.*|BOARD_NAME=\"${bd_name}\"|g" ${armbian_image_file}
        }

        short_version="$(cat ${armbian_image_file} | grep -E '^VERSION=' | grep -oE '[2-9][0-9]\.[0-9]{1,2}\.[0-9]{1,2}' | head -n 1 || true)"
        [[ -n "${short_version}" ]] && {
            sed -i "s|^VERSION=.*|VERSION=\"${short_version}\"|g" ${armbian_image_file}
            sed -i "s|^REVISION=.*|REVISION=\"${short_version}\"|g" ${armbian_image_file}
        }

        sed -i "s|^BOARDFAMILY=.*|BOARDFAMILY=\"${family_name}\"|g" ${armbian_image_file}
        sed -i "s|^LINUXFAMILY=.*|LINUXFAMILY=\"${platform_name}\"|g" ${armbian_image_file}
        sed -i "s|^VENDOR=.*|VENDOR=\"Armbian OS\"|g" ${armbian_image_file}
        sed -i "s|^IMAGE_TYPE=.*|IMAGE_TYPE=rebuild|g" ${armbian_image_file}
        sed -i "s|^BOARD_TYPE=.*|BOARD_TYPE=diy|g" ${armbian_image_file}
        sed -i "s|^FORCE_BOOTSCRIPT_UPDATE=.*|FORCE_BOOTSCRIPT_UPDATE=\"no\"|g" ${armbian_image_file}
        sed -i "s|^BOOTSCRIPT_FORCE_UPDATE=.*|BOOTSCRIPT_FORCE_UPDATE=\"no\"|g" ${armbian_image_file}
        tolog "86. Update custom board info: ${armbian_image_file}"
    }

    # Update os-release information
    [[ -f "${os_release_file}" ]] && {
        short_version="$(cat ${os_release_file} | grep -E '^PRETTY_NAME=' | grep -oE '[2-9][0-9]\.[0-9]{1,2}\.[0-9]{1,2}' | head -n 1 || true)"
        sed -i "s|^PRETTY_NAME=.*|PRETTY_NAME=\"Armbian OS ${short_version} ${DISTRIBUTION_CODENAME}\"|g" ${os_release_file}
        sed -i "s|^ARMBIAN_PRETTY_NAME=.*|ARMBIAN_PRETTY_NAME=\"Armbian OS ${short_version} ${DISTRIBUTION_CODENAME}\"|g" ${os_release_file}
        tolog "87. Update custom board info: ${os_release_file}"
    }

    # Disable unused serial console on non-Amlogic platforms
    [[ "${platform_name}" != "amlogic" ]] && {
        systemctl disable serial-getty@ttyFIQ0 2>/dev/null
        systemctl disable serial-getty@ttyAML0 2>/dev/null
        tolog "88. Disable ttyFIQ0 & ttyAML0 (ttyS2)"
    }
} || true

# Set system distribution status to supported
[[ -n "${DISTRIBUTION_CODENAME}" && -f "${armbian_os_status}" ]] && {
    sed -i "s|^${DISTRIBUTION_CODENAME}=.*|${DISTRIBUTION_CODENAME}=supported|g" ${armbian_os_status}
    tolog "90. Set ${DISTRIBUTION_CODENAME} distribution status to supported"
} || true

# Expand root partition if flagged
todo_rootfs_resize="/root/.no_rootfs_resize"
[[ -f "${todo_rootfs_resize}" && "$(cat ${todo_rootfs_resize} 2>/dev/null | xargs)" == "yes" ]] && {
    armbian-tf 2>/dev/null &&
        tolog "91. Root partition expanded successfully"
} || true

# Hide WAN & IPv6 addresses from MOTD
ip_info_file="/etc/update-motd.d/20-ip-info"
[[ -f "${ip_info_file}" ]] && {
    sed -i '/^get_wan.*_address/s/{.*/{ true; }/' ${ip_info_file}
    sed -i '/if.*ipv6s.*||.*wan6/,/fi/s/^/#/' ${ip_info_file}
    tolog "92. Hide WAN & IPv6 addresses from MOTD"
} || true

# Show end message
tolog "All system fixes applied successfully."
