#!/bin/bash
#==============================================================================================
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the Rebuild Armbian
# https://github.com/ophub/amlogic-s9xxx-armbian
#
# Description: Third-party software install/update/remove management center
# Copyright (C) 2021- https://github.com/unifreq
# Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
#
# Command: armbian-software
#
#======================================= Functions list =======================================
#
# error_msg               : Output error message
# check_release           : Check system release information
# check_depends           : Check and install runtime dependencies
# check_software_status   : Initialize and check software status
# search_software_model   : Search for software model by ID
# show_software_list      : Display the software list
# update_script           : Update software management scripts
# clean_tmp               : Clear temporary files
# help_info               : Show help information
#
#=============================== Set make environment variables ===============================
#
# Related file storage path
software_path="/usr/share/ophub/armbian-software"
software_conf="${software_path}/software-list.conf"
ophub_release_file="/etc/ophub-release"
arch_info="$(arch)"
#
# The software management scripts download repository
script_repo="https://github.com/ophub/amlogic-s9xxx-armbian.git"
script_dir="build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software"
#
# Set font color
STEPS="[\033[95m STEPS \033[0m]"
INFO="[\033[94m INFO \033[0m]"
SUCCESS="[\033[92m SUCCESS \033[0m]"
OPTIONS="[\033[93m OPTIONS \033[0m]"
ERROR="[\033[91m ERROR \033[0m]"
#
#==============================================================================================

# Show error message
error_msg() {
    echo -e "${ERROR} ${1}"
    exit 1
}

# Check system release information
check_release() {
    if [[ -f "${ophub_release_file}" ]]; then
        source "${ophub_release_file}" 2>/dev/null
        VERSION_CODEID="${VERSION_CODEID}"
        VERSION_CODENAME="${VERSION_CODENAME}"
    else
        error_msg "Missing release file: [ ${ophub_release_file} ]"
    fi

    [[ -n "${VERSION_CODEID}" && -n "${VERSION_CODENAME}" ]] || error_msg "Incomplete release info in [ ${ophub_release_file} ]"
}

# Check and install required dependencies
check_depends() {
    # List of required dependencies
    dpkg_packages=(
        "apt-transport-https" "ca-certificates" "coreutils" "cpu-checker" "curl"
        "dmidecode" "dnsmasq-base" "git" "net-tools" "systemd" "tar"
    )
    # Add additional dependencies for non-trixie versions
    if [[ "${VERSION_CODENAME}" != "trixie" ]]; then
        dpkg_packages+=("software-properties-common")
    fi

    # Cyclic check all dependencies
    is_dpkg="0"
    i="1"
    for package in ${dpkg_packages[*]}; do
        [[ -n "$(dpkg -l | awk '{print $2}' | grep -w "^${package}$")" ]] || is_dpkg="1"
        #echo -e "${INFO} ${package}: ${is_dpkg}"
        ((i++))
    done
    # Install missing packages
    if [[ "${is_dpkg}" -eq "1" ]]; then
        echo -e "${STEPS} Installing required dependencies..."
        sudo apt-get update
        sudo apt-get install -y ${dpkg_packages[*]}
        [[ "${?}" -eq "0" ]] || error_msg "Failed to install dependencies."
    fi
}

# Initialize and check software installation status
check_software_status() {
    # Check if the software configuration file exists
    [[ -s "${software_conf}" ]] || error_msg "Missing configuration file: [ ${software_conf} ]"
    [[ -n "$(cat ${software_conf} | grep -E "^[0-9]{1,9}.*:")" ]] || error_msg "Configuration file is empty: [ ${software_conf} ]"

    # Check software installation status
    tmp_conf="$(mktemp)"
    [[ -f "${tmp_conf}" ]] && rm -f ${tmp_conf} 2>/dev/null
    cat ${software_conf} 2>/dev/null | grep -E "^[0-9]{1,9}.*:" | sed -e 's/NA//g' -e 's/NULL//g' -e 's/[ ][ ]*//g' | while read line; do
        # Set initial value
        local state="not-installed"
        local manage="install"
        local support="supported"
        # Check software installation status
        local auth_method="$(echo ${line} | awk -F ':' '{print $3}' | awk -F '@' '{print $1}')"
        local package="$(echo ${line} | awk -F ':' '{print $3}' | awk -F '@' '{print $2}')"
        # Check the software installation status by category
        check_status="0"
        case "${auth_method}" in
        dpkg) [[ -n "$(dpkg -l | awk '{print $2}' | grep -w "^${package}$" 2>/dev/null)" ]] && check_status="1" ;;
        docker) [[ -n "$(docker ps -q -f name=${package} 2>/dev/null)" ]] && check_status="1" ;;
        which) [[ -n "$(which "${package}" 2>/dev/null)" ]] && check_status="1" ;;
        find) [[ -s "${package}" ]] && check_status="1" ;;
        *) check_status="0" ;;
        esac
        # Adjust software installation status
        [[ "${check_status}" -eq "1" ]] && {
            local state="installed"
            local manage="update/remove"
        }

        # Check whether the software supports running on the current system
        local release="$(echo ${line} | awk -F ':' '{print $5}')"
        [[ "${release}" != "all" && "${release}" != *"${VERSION_CODENAME}"* ]] && {
            local support="unsupported"
            local manage="-"
        }

        # Query results are written to a temporary file
        [[ "${support}" == "supported" ]] && echo "${line}:${support}:${state}:${manage}" >>${tmp_conf} && sync
    done
    software_database="$(cat ${tmp_conf} 2>/dev/null)"
    [[ -n "${software_database}" ]] || error_msg "No compatible software found for [ ${VERSION_CODEID}:${VERSION_CODENAME} ]."
}

# Search for software model by ID
search_software_model() {
    local sid="${1}"
    local ret_count="$(echo "${software_database}" | grep -E "^${sid}:" | wc -l)"
    if [[ "${ret_count}" -eq "1" ]]; then
        echo "${software_database}" | grep -E "^${sid}:"
    fi
}

# Display the software list and handle user selection
# Columns: 1.ID   2.NAME   3.STATE          4.MANAGE
# Example: 11     :frps    :not-installed   :install
show_software_list() {
    echo -e "${STEPS} Displaying software list [ System: \033[92m${VERSION_CODEID}/${VERSION_CODENAME}\033[0m ]..."

    # Check software status
    check_software_status

    # Define split line style
    split_line="───────────────────────────────────────────────────────────────────"
    # Show software list
    echo "${software_database}" | awk -F ':' '{print $1,$2,$7,$8}' | while read line; do
        # Add a header for each software list category
        [[ "$(echo ${line} | awk '{print $1}')" == *"01" ]] && {
            printf "%-s\n" "${split_line}"
            printf "%-5s %-30s %-15s %-15s\n" ID NAME STATE MANAGE
            printf "%-s\n" "${split_line}"
        }
        # Print software information
        printf "%-5s %-30s %-15s %-15s\n" $(echo "${line}")
    done
    # Add end split line
    printf "%-s\n" "${split_line}"

    # Display software options
    echo -ne "${OPTIONS} Please Input Software ID: "
    read software_id
    # Check the validity of the selection
    ret="$(search_software_model "${software_id}")"
    [[ -z "${ret}" ]] && error_msg "Software ID [ ${software_id} ] not found!"
    #echo -e "${INFO} Software Model: [ ${ret} ]"

    # Display selected software information
    software_name="$(echo "${ret}" | awk -F ':' '{print $2}')"
    software_execute="$(echo "${ret}" | awk -F ':' '{print $4}')"
    software_release="$(echo "${ret}" | awk -F ':' '{print $5}')"
    software_support="$(echo "${ret}" | awk -F ':' '{print $6}')"
    software_state="$(echo "${ret}" | awk -F ':' '{print $7}')"
    software_manage="$(echo "${ret}" | awk -F ':' '{print $8}')"
    if [[ "${software_support}" == "supported" ]]; then
        echo -e "${INFO} Software ID: [ ${software_id} ]"
        echo -e "${INFO} Software Name: [ ${software_name} ]"
    else
        error_msg "This software is not compatible with the current system. Supported: [ ${software_release//@/ \| } ]."
    fi

    # Choose to update or remove installed software
    [[ "${software_state}" == "installed" ]] && {
        echo -ne "${OPTIONS} Update=(u) or Remove=(r)? (u/r): "
        read optid
        optid="${optid/U/u}" && optid="${optid/R/r}"
        [[ "${optid:0:1}" == "u" || "${optid:0:1}" == "r" ]] || error_msg "Invalid input!"
        [[ "${optid:0:1}" == "u" ]] && software_manage="update" || software_manage="remove"
    }

    echo -e "${STEPS} Processing: [ ${software_execute} ${software_manage} ${software_name} ]..."

    # Perform software install/update/remove operations
    if [[ "${software_execute}" == "command-"* ]]; then
        # Execute fixed scripts
        sudo bash ${software_path}/${software_execute} -s ${software_id} -m ${software_manage}
    else
        # Execute dedicated scripts
        sudo bash ${software_path}/${software_execute} ${software_manage}
    fi
}

# Update software management scripts from repository
update_script() {
    echo -e "${STEPS} Updating software management scripts..."

    # Download the latest scripts from the repository
    git_tmp_path="$(mktemp -d)"
    cd ${git_tmp_path}
    git init --quiet
    git config core.sparseCheckout true
    echo "${script_dir}/*" >>.git/info/sparse-checkout
    git remote add origin ${script_repo}
    git pull --quiet --depth=1 origin main
    [[ "${?}" -ne "0" ]] && error_msg "Failed to download scripts from [ ${script_repo} ]."

    # Update the software management scripts
    mkdir -p ${software_path}
    cp -af --no-preserve=ownership ${git_tmp_path}/${script_dir}/* ${software_path}
    [[ "${?}" -ne "0" ]] && error_msg "Failed to sync scripts from [ ${script_repo} ]."
    find ${software_path} -type f -name '*.sh' -exec chmod +x {} \;

    # Clean up temporary files
    rm -rf ${git_tmp_path} 2>/dev/null

    sync && sleep 3
    echo -e "${SUCCESS} Scripts updated successfully."
    exit 0
}

# Clear software management scripts and temporary files
clean_tmp() {
    echo -e "${STEPS} Cleaning up software management files..."

    rm -rf ${software_path} 2>/dev/null && sync

    echo -e "${SUCCESS} Cleanup completed successfully."
    exit 0
}

# Show help information
help_info() {
    clear
    cat <<EOF
======================================================================
Command Example : armbian-software -u
             -u : Update    Update install software script.
             -c : Clear     Clear the local install software script.
             -h : Help      Help information display.
             -q : Quit      Quit install software services.
              * : Other     Show software list.
======================================================================
EOF
    exit 0
}

# Check script permission, only supports running on Armbian (aarch64)
[[ "$(id -u)" == "0" ]] || error_msg "Please run this script as root: [ sudo $0 ]"
[[ "${arch_info}" == "aarch64" ]] || error_msg "This script only supports running on Armbian (aarch64) systems."
# Ensure the software configuration file exists
[[ -f "${software_conf}" ]] || echo -e "${INFO} Please run [ armbian-software -u ] to update the software management scripts."
# Check system release information
check_release
# Check and install runtime dependencies
check_depends

# Execute script assist functions
case "${1}" in
-u | -update) update_script ;;
-c | -clean) clean_tmp ;;
-h | -help) help_info ;;
-q | -quit) echo "quit!" && exit 0 ;;
*) show_software_list ;;
esac
