#!/bin/bash
#=========================================================================
# Description: Install docker to armbian
# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
#=========================================================================

# Install the necessary system tools
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

# Install GPG certificate
curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/debian/gpg | apt-key add -

# Add software source information
sudo add-apt-repository "deb [arch=amd64,armhf] https://mirrors.aliyun.com/docker-ce/linux/debian $(lsb_release -cs) stable"

# Update and install Docker
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# Configure Docker to start automatically after booting
sudo systemctl enable docker.service
sudo systemctl enable containerd.service

# Set up ordinary users to run docker directly
sudo usermod -aG docker $USER
newgrp docker

# Save Settings
rm -f /etc/apt/sources.list.save 2>/dev/null
rm -f /etc/apt/*.gpg~ 2>/dev/null
sync
exit 0
