[/sys/class/leds/mmc0::]
trigger=mmc0
brightness=0

[/sys/class/leds/power_green]
trigger=none
brightness=1

[/sys/class/leds/power_red]
trigger=none
brightness=0

[/sys/class/leds/sata0_green]
trigger=none
brightness=0

[/sys/class/leds/sata0_red]
trigger=none
brightness=0

[/sys/class/leds/sata1_green]
trigger=none
brightness=0

[/sys/class/leds/sata1_red]
trigger=none
brightness=0
