#!/bin/bash
#=====================================================================================
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the Armbian for Amlogic TV Boxes
# https://github.com/ophub/amlogic-s9xxx-armbian
#
# Dependent script: /usr/lib/armbian/armbian-firstrun
# Function: Fix permissions and related settings(Executed at system initialization)
# Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
#
# Command: armbian-fix
#
#=====================================================================================

# Fix common releases permissions
[[ -d "/var/tmp" ]] && sudo chmod 777 /var/tmp && echo "01. Fix tmp permissions"
[[ -d "/etc/update-motd.d" ]] && sudo chmod 755 /etc/update-motd.d/* && echo "02. Fix update-motd.d permissions"
[[ -d "/var/cache/man" ]] && sudo chown man:root /var/cache/man -R && echo "03. Fix man permissions"
[[ -d "/var/cache/man" ]] && sudo chmod g+s /var/cache/man -R && echo "04. Fix man permissions"
[[ -f "/usr/bin/sudo" ]] && sudo chown root:root /usr/bin/sudo && echo "05. Fix sudo permissions"
[[ -f "/usr/bin/sudo" ]] && sudo chmod 4755 /usr/bin/sudo && echo "06. Fix sudo permissions"
# Fix focal permissions
[[ -f "/usr/lib/sudo/sudoers.so" ]] && sudo chown 0 /usr/lib/sudo/sudoers.so && echo "07. Fix sudoers.so permissions"
[[ -f "/usr/lib/sudo/sudoers.so" ]] && sudo chmod 644 /usr/lib/sudo/sudoers.so && echo "08. Fix sudoers.so permissions"
[[ -f "/usr/lib/policykit-1/polkit-agent-helper-1" ]] && sudo chmod 4755 /usr/lib/policykit-1/polkit-agent-helper-1 && echo "09. Fix polkit-agent-helper-1 permissions"
# Fix jammy permissions
[[ -f "/usr/libexec/sudo/sudoers.so" ]] && sudo chown 0 /usr/libexec/sudo/sudoers.so && echo "10. Fix sudoers.so permissions"
[[ -f "/usr/libexec/sudo/sudoers.so" ]] && sudo chmod 644 /usr/libexec/sudo/sudoers.so && echo "11. Fix sudoers.so permissions"
[[ -f "/usr/libexec/polkit-agent-helper-1" ]] && sudo chmod 4755 /usr/libexec/polkit-agent-helper-1 && echo "12. Fix polkit-agent-helper-1 permissions"

# Remove packages
[[ -n "$(dpkg -l | grep linux-image-edge-meson64)" ]] && sudo apt-get -qq purge -y linux-image-edge-meson64 && echo "Remove linux-image-edge-meson64"
[[ -n "$(dpkg -l | grep linux-image-current-meson64)" ]] && sudo apt-get -qq purge -y linux-image-current-meson64 && echo "Remove linux-image-current-meson64"
[[ -n "$(dpkg -l | grep linux-image-legacy-meson64)" ]] && sudo apt-get -qq purge -y linux-image-legacy-meson64 && echo "Remove linux-image-legacy-meson64"
[[ -n "$(dpkg -l | grep linux-dtb-edge-meson64)" ]] && sudo apt-get -qq purge -y linux-dtb-edge-meson64 && echo "Remove linux-dtb-edge-meson64"
[[ -n "$(dpkg -l | grep linux-dtb-current-meson64)" ]] && sudo apt-get -qq purge -y linux-dtb-current-meson64 && echo "Remove linux-dtb-current-meson64"
[[ -n "$(dpkg -l | grep linux-dtb-legacy-meson64)" ]] && sudo apt-get -qq purge -y linux-dtb-legacy-meson64 && echo "Remove linux-dtb-legacy-meson64"

sync && echo "armbian-fix: Loading finished."
