# lirc 守护进程配置文件
# 飞牛EasePi-R2默认配置

[lircd]
nodaemon        = False
driver          = default
device          = /dev/lirc0
output          = /var/run/lirc/lircd
pidfile         = /var/run/lirc/lircd.pid
listen          = 0.0.0.0:8765
connect         = 127.0.0.1
# config file 会自动去/etc/lirc/lircd.conf找
